# Generated by Django 4.0.6 on 2022-08-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_borrow_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='return_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrowed_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
